name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag apache-ubuntu-image:$(date +%s)
      
    - name: Generate Deployment Package
      run: zip -r deploy.zip *
      
