name: Docker Image CI

on:
  push:
    tags:        
      - v*.*

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
          
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.DOCKER_HUB_USERNAME }}/apache2-image
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: apach_user_pass=${{ secrets.APACHE_USER_PASS }}
          
    - name: Get tags
      id: get_version
      run: |
        echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
        
    - name: Get version tag
      run: |
        echo ${{ steps.get_version.outputs.VERSION }}
        last_version_ubuntu=${{ steps.get_version.outputs.VERSION }}
          
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -var 'latest_ubuntu_version=${{ steps.get_version.outputs.VERSION }}'

    - name: Terraform Apply
      id: apply
      run: |
        terraform apply -var 'latest_ubuntu_version=${{ steps.get_version.outputs.VERSION }}' --auto-approve


      

          

          
      
